export interface ServiceItem {
  label: string;
  industry: string;
}

export const SERVICES: ServiceItem[] = [
  { label: 'Accounting', industry: 'Accounting / Finance / Audit' },
  { label: 'Audit & Assurance', industry: 'Accounting / Finance / Audit' },
  { label: 'Bookkeeping', industry: 'Accounting / Finance / Audit' },
  { label: 'Debt Consulting', industry: 'Accounting / Finance / Audit' },
  { label: 'Financial Planning', industry: 'Accounting / Finance / Audit' },
  { label: 'Payroll Services', industry: 'Accounting / Finance / Audit' },
  { label: 'Tax Filing', industry: 'Accounting / Finance / Audit' },
  { label: 'Tax Planning', industry: 'Accounting / Finance / Audit' },
  { label: 'Advertising', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Brand Strategy', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Content Marketing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Copywriting', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Digital Marketing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Influencer Marketing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'PR / Public Relations', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'SEO / SEM', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Social Media Marketing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Architecture', industry: 'Architecture / Interior Design' },
  { label: 'Interior Design', industry: 'Architecture / Interior Design' },
  { label: 'Space Planning', industry: 'Architecture / Interior Design' },
  { label: 'AI / Machine Learning', industry: 'Computer / IT / Software' },
  { label: 'Blockchain / Crypto Development', industry: 'Computer / IT / Software' },
  { label: 'Cloud Computing', industry: 'Computer / IT / Software' },
  { label: 'Cybersecurity', industry: 'Computer / IT / Software' },
  { label: 'Data Analytics', industry: 'Computer / IT / Software' },
  { label: 'Data Recovery', industry: 'Computer / IT / Software' },
  { label: 'Desktop Application', industry: 'Computer / IT / Software' },
  { label: 'E-commerce Development', industry: 'Computer / IT / Software' },
  { label: 'ERP / CRM Systems', industry: 'Computer / IT / Software' },
  { label: 'Game Development', industry: 'Computer / IT / Software' },
  { label: 'IoT Solutions', industry: 'Computer / IT / Software' },
  { label: 'IT Consulting', industry: 'Computer / IT / Software' },
  { label: 'IT Project Management', industry: 'Computer / IT / Software' },
  { label: 'IT Support & Helpdesk', industry: 'Computer / IT / Software' },
  { label: 'Mobile App Development', industry: 'Computer / IT / Software' },
  { label: 'Network & Infrastructure', industry: 'Computer / IT / Software' },
  { label: 'QA / Software Testing', industry: 'Computer / IT / Software' },
  { label: 'RPA / Process Automation', industry: 'Computer / IT / Software' },
  { label: 'Software Development', industry: 'Computer / IT / Software' },
  { label: 'Web Development', industry: 'Computer / IT / Software' },
  { label: 'Website Maintenance', industry: 'Computer / IT / Software' },
  { label: 'WordPress Development', industry: 'Computer / IT / Software' },
  { label: 'Business Consulting', industry: 'Consulting / Business Advisory' },
  { label: 'Management Consulting', industry: 'Consulting / Business Advisory' },
  { label: 'Market Research', industry: 'Consulting / Business Advisory' },
  { label: 'Operations Consulting', industry: 'Consulting / Business Advisory' },
  { label: 'Strategy Consulting', industry: 'Consulting / Business Advisory' },
  { label: 'Survey & Research', industry: 'Consulting / Business Advisory' },
  { label: 'Civil Engineering', industry: 'Construction / Engineering' },
  { label: 'Construction', industry: 'Construction / Engineering' },
  { label: 'Project Management', industry: 'Construction / Engineering' },
  { label: 'Renovation', industry: 'Construction / Engineering' },
  { label: 'Art & Illustration', industry: 'Design / Creative' },
  { label: 'Branding & Identity', industry: 'Design / Creative' },
  { label: 'Graphic Design', industry: 'Design / Creative' },
  { label: 'Motion Graphics', industry: 'Design / Creative' },
  { label: 'Packaging Design', industry: 'Design / Creative' },
  { label: 'Presentation Design', industry: 'Design / Creative' },
  { label: 'UI/UX Design', industry: 'Design / Creative' },
  { label: 'Coaching', industry: 'Education / Training' },
  { label: 'Corporate Training', industry: 'Education / Training' },
  { label: 'E-Learning', industry: 'Education / Training' },
  { label: 'Language Instruction', industry: 'Education / Training' },
  { label: 'Private Tutoring', industry: 'Education / Training' },
  { label: 'Catering', industry: 'Event Management' },
  { label: 'Conference & MICE', industry: 'Event Management' },
  { label: 'Corporate Events', industry: 'Event Management' },
  { label: 'DJ / Entertainment', industry: 'Event Management' },
  { label: 'Event Emcee / MC', industry: 'Event Management' },
  { label: 'Event Management', industry: 'Event Management' },
  { label: 'Exhibition Organizer', industry: 'Event Management' },
  { label: 'Floral Design', industry: 'Event Management' },
  { label: 'Stage & Lighting', industry: 'Event Management' },
  { label: 'Talent Booking', industry: 'Event Management' },
  { label: 'Venue Sourcing', industry: 'Event Management' },
  { label: 'Corporate Wellness', industry: 'Healthcare / Medical / Wellness' },
  { label: 'Healthcare Consulting', industry: 'Healthcare / Medical / Wellness' },
  { label: 'Occupational Health', industry: 'Healthcare / Medical / Wellness' },
  { label: 'Event Staffing', industry: 'HR / Recruitment' },
  { label: 'Executive Search', industry: 'HR / Recruitment' },
  { label: 'HR Consulting', industry: 'HR / Recruitment' },
  { label: 'Recruitment', industry: 'HR / Recruitment' },
  { label: 'Temporary Staffing', industry: 'HR / Recruitment' },
  { label: 'Business Licensing', industry: 'Legal / Law / Compliance' },
  { label: 'Company Registration', industry: 'Legal / Law / Compliance' },
  { label: 'Contract Review', industry: 'Legal / Law / Compliance' },
  { label: 'FDA / Regulatory Filing', industry: 'Legal / Law / Compliance' },
  { label: 'Legal Consulting', industry: 'Legal / Law / Compliance' },
  { label: 'Patent & Trademark', industry: 'Legal / Law / Compliance' },
  { label: 'Visa & Work Permit', industry: 'Legal / Law / Compliance' },
  { label: 'Freight & Shipping', industry: 'Logistics / Supply Chain' },
  { label: 'Logistics', industry: 'Logistics / Supply Chain' },
  { label: 'Supply Chain Consulting', industry: 'Logistics / Supply Chain' },
  { label: 'AC Service & Repair', industry: 'Maintenance / Technical Services' },
  { label: 'Electrical Services', industry: 'Maintenance / Technical Services' },
  { label: 'Facility Maintenance', industry: 'Maintenance / Technical Services' },
  { label: 'Pest Control', industry: 'Maintenance / Technical Services' },
  { label: 'Plumbing Services', industry: 'Maintenance / Technical Services' },
  { label: 'Repair Services', industry: 'Maintenance / Technical Services' },
  { label: 'Clothing Manufacturing', industry: 'Manufacturing / OEM' },
  { label: 'Cosmetics Manufacturing', industry: 'Manufacturing / OEM' },
  { label: 'Food & Supplement Manufacturing', industry: 'Manufacturing / OEM' },
  { label: 'OEM / Contract Manufacturing', industry: 'Manufacturing / OEM' },
  { label: 'Packaging Manufacturing', industry: 'Manufacturing / OEM' },
  { label: 'Animation', industry: 'Media / Photography / Video' },
  { label: 'Color Grading', industry: 'Media / Photography / Video' },
  { label: 'Drone Photography', industry: 'Media / Photography / Video' },
  { label: 'Live Streaming', industry: 'Media / Photography / Video' },
  { label: 'Photography', industry: 'Media / Photography / Video' },
  { label: 'Podcast Production', industry: 'Media / Photography / Video' },
  { label: 'Product Photography', industry: 'Media / Photography / Video' },
  { label: 'Subtitling', industry: 'Media / Photography / Video' },
  { label: 'VFX & CGI', industry: 'Media / Photography / Video' },
  { label: 'Video Editing', industry: 'Media / Photography / Video' },
  { label: 'Video Production', industry: 'Media / Photography / Video' },
  { label: 'Videography', industry: 'Media / Photography / Video' },
  { label: 'Audio Recording', industry: 'Music / Audio' },
  { label: 'Jingle Production', industry: 'Music / Audio' },
  { label: 'Mixing & Mastering', industry: 'Music / Audio' },
  { label: 'Music Production', industry: 'Music / Audio' },
  { label: 'Sound Design', industry: 'Music / Audio' },
  { label: 'Sound Engineering', industry: 'Music / Audio' },
  { label: 'Voiceover', industry: 'Music / Audio' },
  { label: 'Brochure & Flyer', industry: 'Print / Production' },
  { label: 'Printing', industry: 'Print / Production' },
  { label: 'Signage', industry: 'Print / Production' },
  { label: 'Property Management', industry: 'Real Estate / Property' },
  { label: 'Real Estate Consulting', industry: 'Real Estate / Property' },
  { label: 'Bodyguard', industry: 'Security / Safety' },
  { label: 'Security Services', industry: 'Security / Safety' },
  { label: 'Interpretation', industry: 'Translation / Localization' },
  { label: 'Localization', industry: 'Translation / Localization' },
  { label: 'Proofreading', industry: 'Translation / Localization' },
  { label: 'Translation', industry: 'Translation / Localization' },
  { label: 'Hospitality Consulting', industry: 'Travel / Tourism / Hospitality' },
  { label: 'Tourism Planning', industry: 'Travel / Tourism / Hospitality' },
  { label: 'Car Rental', industry: 'Vehicle Rental' },
  { label: 'Van Rental', industry: 'Vehicle Rental' },
  { label: 'Vehicle Rental', industry: 'Vehicle Rental' },
  { label: 'Article Writing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Script Writing', industry: 'Advertising / Marketing / Promotion / PR' },
  { label: 'Brand Distribution / Sole Agent', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Cross-border E-commerce', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Franchise Distribution', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Import / Export', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Product Distribution', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Wholesale Trading', industry: 'Trading / Distribution / Import-Export' },
  { label: 'Brand Licensing / IP Licensing', industry: 'Consumer Goods / Brand Management' },
  { label: 'Consumer Brand Management', industry: 'Consumer Goods / Brand Management' },
  { label: 'E-commerce Brand Management', industry: 'Consumer Goods / Brand Management' },
  { label: 'Private Label / House Brand', industry: 'Consumer Goods / Brand Management' },
  { label: 'Product Portfolio Management', industry: 'Consumer Goods / Brand Management' },
  { label: 'Retail Channel Management', industry: 'Consumer Goods / Brand Management' },
  { label: 'Office Cleaning', industry: 'Cleaning / Facility Services' },
  { label: 'Deep Cleaning & Disinfection', industry: 'Cleaning / Facility Services' },
  { label: 'Janitorial Services', industry: 'Cleaning / Facility Services' },
  { label: 'Facility Management', industry: 'Cleaning / Facility Services' },
  { label: 'Waste Management', industry: 'Cleaning / Facility Services' },
  { label: 'Landscaping & Gardening', industry: 'Cleaning / Facility Services' },
  { label: 'Restaurant Supply', industry: 'Food & Beverage' },
  { label: 'Beverage & Coffee Supply', industry: 'Food & Beverage' },
  { label: 'Bakery & Pastry Supply', industry: 'Food & Beverage' },
  { label: 'Cloud Kitchen Services', industry: 'Food & Beverage' },
  { label: 'Food Safety Consulting', industry: 'Food & Beverage' },
  { label: 'Menu Development', industry: 'Food & Beverage' },
  { label: 'Solar Installation', industry: 'Energy / Solar / Sustainability' },
  { label: 'Energy Audit', industry: 'Energy / Solar / Sustainability' },
  { label: 'ESG & Sustainability Consulting', industry: 'Energy / Solar / Sustainability' },
  { label: 'Carbon Footprint Assessment', industry: 'Energy / Solar / Sustainability' },
  { label: 'Energy Management Systems', industry: 'Energy / Solar / Sustainability' },
  { label: 'Call Center Services', industry: 'Call Center / BPO / Back Office' },
  { label: 'Customer Support Outsourcing', industry: 'Call Center / BPO / Back Office' },
  { label: 'Telemarketing', industry: 'Call Center / BPO / Back Office' },
  { label: 'Virtual Assistant', industry: 'Call Center / BPO / Back Office' },
  { label: 'Data Entry', industry: 'Call Center / BPO / Back Office' },
  { label: 'Back-office Outsourcing', industry: 'Call Center / BPO / Back Office' },
  { label: 'Business Insurance', industry: 'Insurance / Financial Services' },
  { label: 'Insurance Brokerage', industry: 'Insurance / Financial Services' },
  { label: 'Employee Benefits & Group Insurance', industry: 'Insurance / Financial Services' },
  { label: 'Risk Management', industry: 'Insurance / Financial Services' },
  { label: 'Investment & Wealth Advisory', industry: 'Insurance / Financial Services' },
];

export function searchServices(query: string, limit = 8): ServiceItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  // Match the service LABEL only (every typed word must appear in it). This
  // keeps results relevant to what was typed — e.g. "event" surfaces
  // event-labelled services, not every service in the Event Management
  // industry (Catering, DJ, …).
  const tokens = q.split(/\s+/);
  return SERVICES
    .filter(s => {
      const label = s.label.toLowerCase();
      return tokens.every(tok => label.includes(tok));
    })
    .slice(0, limit);
}

export const ALL_INDUSTRIES = Array.from(new Set(SERVICES.map(s => s.industry))).sort();
